--- 
pipelines: 
  - 
    configuration: 
      nodepool: k8_pool
    name: my_first_pipeline
    steps: 
      - 
        configuration: 
          inputResources: 
            - 
              name: myFirstRepo
        execution: 
          onExecute: 
            - "echo $res_myFirstRepo_commitSha"
            - "add_run_variables current_runid=$run_id"
            - "add_run_variables commitSha=$res_myFirstRepo_commitSha"
            - "echo \"Previous run ID is $prev_runid\""
        name: p1_s1
      - 
        configuration: 
          inputSteps: 
            - 
              name: p1_s1
        execution: 
          onExecute: 
            - "echo $current_runid"
        name: p1_s2
        type: Bash
      - 
        configuration: 
          inputSteps: 
            - 
              name: p1_s2
          outputResources: 
            - 
              name: myPropertyBag
        execution: 
          onExecute: 
            - "echo $current_runid"
            - "add_pipeline_variables prev_runid=$run_id"
            - "write_output myPropertyBag commitSha=$commitSha runID=$current_runid"
        name: p1_s3
        type: Bash
  - 
    name: my_second_pipeline
    steps: 
      - 
        configuration: 
          inputResources: 
            - 
              name: myPropertyBag
        execution: 
          onExecute: 
            - "echo \"CommitSha is $res_myPropertyBag_commitSha\""
        name: p2_s1
        type: Bash
resources: 
  - 
    configuration: 
      branches: 
        include: master
      gitProvider: 
        ? 
          .Values.myRepo.gitProvider: ~
        : ~
      path: 
        ? 
          .Values.myRepo.path: ~
        : ~
    name: myFirstRepo
    type: GitRepo
  - 
    configuration: 
      commitSha: 1
      runID: 1
    name: myPropertyBag
    type: PropertyBag
template: true
valuesFilePath: ./values.yml
